// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: tephra/v1/tephra.proto

package tephrapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED      ErrorCode = 0
	ErrorCode_ERROR_CODE_CONFLICT         ErrorCode = 1
	ErrorCode_ERROR_CODE_AFTER_BEYOND_TIP ErrorCode = 2
	ErrorCode_ERROR_CODE_EMPTY            ErrorCode = 3
	ErrorCode_ERROR_CODE_TOO_LARGE        ErrorCode = 4
	ErrorCode_ERROR_CODE_BAD_REQUEST      ErrorCode = 5
	ErrorCode_ERROR_CODE_INTERNAL         ErrorCode = 6
	ErrorCode_ERROR_CODE_SHUTDOWN         ErrorCode = 7
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_CONFLICT",
		2: "ERROR_CODE_AFTER_BEYOND_TIP",
		3: "ERROR_CODE_EMPTY",
		4: "ERROR_CODE_TOO_LARGE",
		5: "ERROR_CODE_BAD_REQUEST",
		6: "ERROR_CODE_INTERNAL",
		7: "ERROR_CODE_SHUTDOWN",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":      0,
		"ERROR_CODE_CONFLICT":         1,
		"ERROR_CODE_AFTER_BEYOND_TIP": 2,
		"ERROR_CODE_EMPTY":            3,
		"ERROR_CODE_TOO_LARGE":        4,
		"ERROR_CODE_BAD_REQUEST":      5,
		"ERROR_CODE_INTERNAL":         6,
		"ERROR_CODE_SHUTDOWN":         7,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_tephra_v1_tephra_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_tephra_v1_tephra_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{0}
}

// A single event: an opaque type string, a set of tag strings, and an opaque payload.
// The server validates these against tephra's own constructors.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// One alternative in a query: types OR'd within the item, tags AND'd within the item.
type QueryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []string               `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryItem) Reset() {
	*x = QueryItem{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryItem) ProtoMessage() {}

func (x *QueryItem) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryItem.ProtoReflect.Descriptor instead.
func (*QueryItem) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{1}
}

func (x *QueryItem) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *QueryItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// A query: the catch-all (all = true) or a set of items OR'd together.
type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Items         []*QueryItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{2}
}

func (x *Query) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *Query) GetItems() []*QueryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// The guard on an append: reject if any event after `after` matches the query.
// `after` = 0 means "consider the whole log" (positions are 1-based).
type AppendCondition struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FailIfEventsMatch *Query                 `protobuf:"bytes,1,opt,name=fail_if_events_match,json=failIfEventsMatch,proto3" json:"fail_if_events_match,omitempty"`
	After             uint64                 `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppendCondition) Reset() {
	*x = AppendCondition{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendCondition) ProtoMessage() {}

func (x *AppendCondition) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendCondition.ProtoReflect.Descriptor instead.
func (*AppendCondition) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{3}
}

func (x *AppendCondition) GetFailIfEventsMatch() *Query {
	if x != nil {
		return x.FailIfEventsMatch
	}
	return nil
}

func (x *AppendCondition) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

type AppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Condition     *AppendCondition       `protobuf:"bytes,2,opt,name=condition,proto3,oneof" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{4}
}

func (x *AppendRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *AppendRequest) GetCondition() *AppendCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// The pagination cursor, taken verbatim in both directions. For a forward read (`reverse` =
	// false) it is an exclusive lower bound: return matches after this position, ascending, and
	// `0` reads from the start. For a backward read (`reverse` = true) it is an exclusive upper
	// bound: return matches before this position, descending; read from the tip by sending the
	// maximum position (`u64::MAX`), and `0` therefore returns nothing (before the first position).
	After uint64 `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	// Caps the number of matched events returned. Absent means unlimited (an old client, which
	// never sets it, keeps the full-history behavior); explicit presence distinguishes a real
	// cap of 0 (return nothing) from "no cap". Composes with `after` as a stateless pagination
	// cursor: read a page, then read again with `after` set to the last position returned (the
	// oldest, for a backward read).
	Limit *uint64 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Read backwards: matched events descending by position, before the `after` cursor. Defaults
	// to false, so an old client that never sets it keeps the forward, ascending behavior.
	Reverse       bool `protobuf:"varint,4,opt,name=reverse,proto3" json:"reverse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{5}
}

func (x *ReadRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ReadRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *ReadRequest) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ReadRequest) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

// Opens a live subscription: catch up on all events matching `query` after `after`, then
// tail new ones as they are committed. The server streams `ReadEvents` batches and a
// `SubscribeCaughtUp` marker each time the stream reaches the live edge. A subscription never
// ends with a `ReadEnd`; it terminates only when the connection closes or errors.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	After         uint64                 `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SubscribeRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

// Cancels an in-flight request on the same connection, identified by its request id. Sent by
// a multiplexed client to stop a streaming read or subscription without tearing down the
// shared connection. Fire-and-forget: the server stops producing frames for `target` and
// sends no response for the cancel itself.
type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        uint64                 `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{7}
}

func (x *CancelRequest) GetTarget() uint64 {
	if x != nil {
		return x.Target
	}
	return 0
}

// Asks the server for a point-in-time snapshot of its operational state.
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{8}
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         uint64                 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Last          uint64                 `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{9}
}

func (x *AppendResponse) GetFirst() uint64 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *AppendResponse) GetLast() uint64 {
	if x != nil {
		return x.Last
	}
	return 0
}

type SequencedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      uint64                 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequencedEvent) Reset() {
	*x = SequencedEvent{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequencedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencedEvent) ProtoMessage() {}

func (x *SequencedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencedEvent.ProtoReflect.Descriptor instead.
func (*SequencedEvent) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{10}
}

func (x *SequencedEvent) GetPosition() uint64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *SequencedEvent) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// A streamed batch of events for a read. Zero or more of these precede a ReadEnd.
type ReadEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*SequencedEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEvents) Reset() {
	*x = ReadEvents{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEvents) ProtoMessage() {}

func (x *ReadEvents) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEvents.ProtoReflect.Descriptor instead.
func (*ReadEvents) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{11}
}

func (x *ReadEvents) GetEvents() []*SequencedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// Terminates a successful read, carrying the watermark the read was pinned to.
type ReadEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watermark     uint64                 `protobuf:"varint,1,opt,name=watermark,proto3" json:"watermark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEnd) Reset() {
	*x = ReadEnd{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEnd) ProtoMessage() {}

func (x *ReadEnd) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEnd.ProtoReflect.Descriptor instead.
func (*ReadEnd) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{12}
}

func (x *ReadEnd) GetWatermark() uint64 {
	if x != nil {
		return x.Watermark
	}
	return 0
}

// Sent on a subscription each time it drains all events up to the current watermark and is
// about to tail live. Re-armed: emitted once per live-edge, with non-decreasing watermarks.
type SubscribeCaughtUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watermark     uint64                 `protobuf:"varint,1,opt,name=watermark,proto3" json:"watermark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeCaughtUp) Reset() {
	*x = SubscribeCaughtUp{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeCaughtUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeCaughtUp) ProtoMessage() {}

func (x *SubscribeCaughtUp) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeCaughtUp.ProtoReflect.Descriptor instead.
func (*SubscribeCaughtUp) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeCaughtUp) GetWatermark() uint64 {
	if x != nil {
		return x.Watermark
	}
	return 0
}

// A snapshot of the server's operational state, the reply to a StatsRequest.
type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total durable events, which (positions being dense and 1-based) is also the tip position.
	EventCount uint64 `protobuf:"varint,1,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	// On-disk log segments in the data directory.
	SegmentCount uint64 `protobuf:"varint,2,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	// Total bytes on disk in the data directory (log segments plus index sidecars).
	DiskBytes uint64 `protobuf:"varint,3,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	// Seconds since the server began accepting connections.
	UptimeSeconds uint64 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Connections currently being served (including the one asking).
	ActiveConnections uint64 `protobuf:"varint,5,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	// Live subscriptions across all connections.
	ActiveSubscriptions uint64 `protobuf:"varint,6,opt,name=active_subscriptions,json=activeSubscriptions,proto3" json:"active_subscriptions,omitempty"`
	// The server's crate version.
	Version string `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	// Connections refused because the server was at its connection cap. Monotonic.
	ConnectionsRefused uint64 `protobuf:"varint,8,opt,name=connections_refused,json=connectionsRefused,proto3" json:"connections_refused,omitempty"`
	// The configured maximum concurrent connections, or 0 when unlimited.
	MaxConnections uint64 `protobuf:"varint,9,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	// Connections reaped for exceeding a handshake, idle, or incomplete-frame timeout. Monotonic.
	ConnectionsReaped uint64 `protobuf:"varint,10,opt,name=connections_reaped,json=connectionsReaped,proto3" json:"connections_reaped,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{14}
}

func (x *StatsResponse) GetEventCount() uint64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *StatsResponse) GetSegmentCount() uint64 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *StatsResponse) GetDiskBytes() uint64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *StatsResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatsResponse) GetActiveConnections() uint64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *StatsResponse) GetActiveSubscriptions() uint64 {
	if x != nil {
		return x.ActiveSubscriptions
	}
	return 0
}

func (x *StatsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatsResponse) GetConnectionsRefused() uint64 {
	if x != nil {
		return x.ConnectionsRefused
	}
	return 0
}

func (x *StatsResponse) GetMaxConnections() uint64 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *StatsResponse) GetConnectionsReaped() uint64 {
	if x != nil {
		return x.ConnectionsReaped
	}
	return 0
}

type ErrorResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=tephra.v1.ErrorCode" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Set for a durable append conflict: the position of the conflicting event.
	ConflictPosition *uint64 `protobuf:"varint,3,opt,name=conflict_position,json=conflictPosition,proto3,oneof" json:"conflict_position,omitempty"`
	// A same-batch conflict is advisory and retryable; a durable one is terminal.
	Retryable     bool `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{15}
}

func (x *ErrorResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetConflictPosition() uint64 {
	if x != nil && x.ConflictPosition != nil {
		return *x.ConflictPosition
	}
	return 0
}

func (x *ErrorResponse) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type Request struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Request_Append
	//	*Request_Read
	//	*Request_Subscribe
	//	*Request_Cancel
	//	*Request_Stats
	Kind          isRequest_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{16}
}

func (x *Request) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Request) GetKind() isRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Request) GetAppend() *AppendRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Append); ok {
			return x.Append
		}
	}
	return nil
}

func (x *Request) GetRead() *ReadRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Request) GetSubscribe() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *Request) GetCancel() *CancelRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *Request) GetStats() *StatsRequest {
	if x != nil {
		if x, ok := x.Kind.(*Request_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

type isRequest_Kind interface {
	isRequest_Kind()
}

type Request_Append struct {
	Append *AppendRequest `protobuf:"bytes,2,opt,name=append,proto3,oneof"`
}

type Request_Read struct {
	Read *ReadRequest `protobuf:"bytes,3,opt,name=read,proto3,oneof"`
}

type Request_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,4,opt,name=subscribe,proto3,oneof"`
}

type Request_Cancel struct {
	Cancel *CancelRequest `protobuf:"bytes,5,opt,name=cancel,proto3,oneof"`
}

type Request_Stats struct {
	Stats *StatsRequest `protobuf:"bytes,6,opt,name=stats,proto3,oneof"`
}

func (*Request_Append) isRequest_Kind() {}

func (*Request_Read) isRequest_Kind() {}

func (*Request_Subscribe) isRequest_Kind() {}

func (*Request_Cancel) isRequest_Kind() {}

func (*Request_Stats) isRequest_Kind() {}

type Response struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Response_Append
	//	*Response_ReadEvents
	//	*Response_ReadEnd
	//	*Response_Error
	//	*Response_CaughtUp
	//	*Response_Stats
	Kind          isResponse_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_tephra_v1_tephra_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_tephra_v1_tephra_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_tephra_v1_tephra_proto_rawDescGZIP(), []int{17}
}

func (x *Response) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Response) GetKind() isResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Response) GetAppend() *AppendResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Append); ok {
			return x.Append
		}
	}
	return nil
}

func (x *Response) GetReadEvents() *ReadEvents {
	if x != nil {
		if x, ok := x.Kind.(*Response_ReadEvents); ok {
			return x.ReadEvents
		}
	}
	return nil
}

func (x *Response) GetReadEnd() *ReadEnd {
	if x != nil {
		if x, ok := x.Kind.(*Response_ReadEnd); ok {
			return x.ReadEnd
		}
	}
	return nil
}

func (x *Response) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Response) GetCaughtUp() *SubscribeCaughtUp {
	if x != nil {
		if x, ok := x.Kind.(*Response_CaughtUp); ok {
			return x.CaughtUp
		}
	}
	return nil
}

func (x *Response) GetStats() *StatsResponse {
	if x != nil {
		if x, ok := x.Kind.(*Response_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

type isResponse_Kind interface {
	isResponse_Kind()
}

type Response_Append struct {
	Append *AppendResponse `protobuf:"bytes,2,opt,name=append,proto3,oneof"`
}

type Response_ReadEvents struct {
	ReadEvents *ReadEvents `protobuf:"bytes,3,opt,name=read_events,json=readEvents,proto3,oneof"`
}

type Response_ReadEnd struct {
	ReadEnd *ReadEnd `protobuf:"bytes,4,opt,name=read_end,json=readEnd,proto3,oneof"`
}

type Response_Error struct {
	Error *ErrorResponse `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type Response_CaughtUp struct {
	CaughtUp *SubscribeCaughtUp `protobuf:"bytes,6,opt,name=caught_up,json=caughtUp,proto3,oneof"`
}

type Response_Stats struct {
	Stats *StatsResponse `protobuf:"bytes,7,opt,name=stats,proto3,oneof"`
}

func (*Response_Append) isResponse_Kind() {}

func (*Response_ReadEvents) isResponse_Kind() {}

func (*Response_ReadEnd) isResponse_Kind() {}

func (*Response_Error) isResponse_Kind() {}

func (*Response_CaughtUp) isResponse_Kind() {}

func (*Response_Stats) isResponse_Kind() {}

var File_tephra_v1_tephra_proto protoreflect.FileDescriptor

const file_tephra_v1_tephra_proto_rawDesc = "" +
	"\n" +
	"\x16tephra/v1/tephra.proto\x12\ttephra.v1\"I\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"5\n" +
	"\tQueryItem\x12\x14\n" +
	"\x05types\x18\x01 \x03(\tR\x05types\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"E\n" +
	"\x05Query\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12*\n" +
	"\x05items\x18\x02 \x03(\v2\x14.tephra.v1.QueryItemR\x05items\"j\n" +
	"\x0fAppendCondition\x12A\n" +
	"\x14fail_if_events_match\x18\x01 \x01(\v2\x10.tephra.v1.QueryR\x11failIfEventsMatch\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x04R\x05after\"\x86\x01\n" +
	"\rAppendRequest\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.tephra.v1.EventR\x06events\x12=\n" +
	"\tcondition\x18\x02 \x01(\v2\x1a.tephra.v1.AppendConditionH\x00R\tcondition\x88\x01\x01B\f\n" +
	"\n" +
	"_condition\"\x8a\x01\n" +
	"\vReadRequest\x12&\n" +
	"\x05query\x18\x01 \x01(\v2\x10.tephra.v1.QueryR\x05query\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x04R\x05after\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x04H\x00R\x05limit\x88\x01\x01\x12\x18\n" +
	"\areverse\x18\x04 \x01(\bR\areverseB\b\n" +
	"\x06_limit\"P\n" +
	"\x10SubscribeRequest\x12&\n" +
	"\x05query\x18\x01 \x01(\v2\x10.tephra.v1.QueryR\x05query\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x04R\x05after\"'\n" +
	"\rCancelRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\x04R\x06target\"\x0e\n" +
	"\fStatsRequest\":\n" +
	"\x0eAppendResponse\x12\x14\n" +
	"\x05first\x18\x01 \x01(\x04R\x05first\x12\x12\n" +
	"\x04last\x18\x02 \x01(\x04R\x04last\"T\n" +
	"\x0eSequencedEvent\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x04R\bposition\x12&\n" +
	"\x05event\x18\x02 \x01(\v2\x10.tephra.v1.EventR\x05event\"?\n" +
	"\n" +
	"ReadEvents\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.tephra.v1.SequencedEventR\x06events\"'\n" +
	"\aReadEnd\x12\x1c\n" +
	"\twatermark\x18\x01 \x01(\x04R\twatermark\"1\n" +
	"\x11SubscribeCaughtUp\x12\x1c\n" +
	"\twatermark\x18\x01 \x01(\x04R\twatermark\"\xa0\x03\n" +
	"\rStatsResponse\x12\x1f\n" +
	"\vevent_count\x18\x01 \x01(\x04R\n" +
	"eventCount\x12#\n" +
	"\rsegment_count\x18\x02 \x01(\x04R\fsegmentCount\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x03 \x01(\x04R\tdiskBytes\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x04R\ruptimeSeconds\x12-\n" +
	"\x12active_connections\x18\x05 \x01(\x04R\x11activeConnections\x121\n" +
	"\x14active_subscriptions\x18\x06 \x01(\x04R\x13activeSubscriptions\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12/\n" +
	"\x13connections_refused\x18\b \x01(\x04R\x12connectionsRefused\x12'\n" +
	"\x0fmax_connections\x18\t \x01(\x04R\x0emaxConnections\x12-\n" +
	"\x12connections_reaped\x18\n" +
	" \x01(\x04R\x11connectionsReaped\"\xb9\x01\n" +
	"\rErrorResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.tephra.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x11conflict_position\x18\x03 \x01(\x04H\x00R\x10conflictPosition\x88\x01\x01\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryableB\x14\n" +
	"\x12_conflict_position\"\xb4\x02\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x122\n" +
	"\x06append\x18\x02 \x01(\v2\x18.tephra.v1.AppendRequestH\x00R\x06append\x12,\n" +
	"\x04read\x18\x03 \x01(\v2\x16.tephra.v1.ReadRequestH\x00R\x04read\x12;\n" +
	"\tsubscribe\x18\x04 \x01(\v2\x1b.tephra.v1.SubscribeRequestH\x00R\tsubscribe\x122\n" +
	"\x06cancel\x18\x05 \x01(\v2\x18.tephra.v1.CancelRequestH\x00R\x06cancel\x12/\n" +
	"\x05stats\x18\x06 \x01(\v2\x17.tephra.v1.StatsRequestH\x00R\x05statsB\x06\n" +
	"\x04kind\"\xf2\x02\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x123\n" +
	"\x06append\x18\x02 \x01(\v2\x19.tephra.v1.AppendResponseH\x00R\x06append\x128\n" +
	"\vread_events\x18\x03 \x01(\v2\x15.tephra.v1.ReadEventsH\x00R\n" +
	"readEvents\x12/\n" +
	"\bread_end\x18\x04 \x01(\v2\x12.tephra.v1.ReadEndH\x00R\areadEnd\x120\n" +
	"\x05error\x18\x05 \x01(\v2\x18.tephra.v1.ErrorResponseH\x00R\x05error\x12;\n" +
	"\tcaught_up\x18\x06 \x01(\v2\x1c.tephra.v1.SubscribeCaughtUpH\x00R\bcaughtUp\x120\n" +
	"\x05stats\x18\a \x01(\v2\x18.tephra.v1.StatsResponseH\x00R\x05statsB\x06\n" +
	"\x04kind*\xdf\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ERROR_CODE_CONFLICT\x10\x01\x12\x1f\n" +
	"\x1bERROR_CODE_AFTER_BEYOND_TIP\x10\x02\x12\x14\n" +
	"\x10ERROR_CODE_EMPTY\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_TOO_LARGE\x10\x04\x12\x1a\n" +
	"\x16ERROR_CODE_BAD_REQUEST\x10\x05\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x06\x12\x17\n" +
	"\x13ERROR_CODE_SHUTDOWN\x10\aB8Z6github.com/tqwewe/tephra-go/internal/tephrapb;tephrapbb\x06proto3"

var (
	file_tephra_v1_tephra_proto_rawDescOnce sync.Once
	file_tephra_v1_tephra_proto_rawDescData []byte
)

func file_tephra_v1_tephra_proto_rawDescGZIP() []byte {
	file_tephra_v1_tephra_proto_rawDescOnce.Do(func() {
		file_tephra_v1_tephra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tephra_v1_tephra_proto_rawDesc), len(file_tephra_v1_tephra_proto_rawDesc)))
	})
	return file_tephra_v1_tephra_proto_rawDescData
}

var file_tephra_v1_tephra_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tephra_v1_tephra_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_tephra_v1_tephra_proto_goTypes = []any{
	(ErrorCode)(0),            // 0: tephra.v1.ErrorCode
	(*Event)(nil),             // 1: tephra.v1.Event
	(*QueryItem)(nil),         // 2: tephra.v1.QueryItem
	(*Query)(nil),             // 3: tephra.v1.Query
	(*AppendCondition)(nil),   // 4: tephra.v1.AppendCondition
	(*AppendRequest)(nil),     // 5: tephra.v1.AppendRequest
	(*ReadRequest)(nil),       // 6: tephra.v1.ReadRequest
	(*SubscribeRequest)(nil),  // 7: tephra.v1.SubscribeRequest
	(*CancelRequest)(nil),     // 8: tephra.v1.CancelRequest
	(*StatsRequest)(nil),      // 9: tephra.v1.StatsRequest
	(*AppendResponse)(nil),    // 10: tephra.v1.AppendResponse
	(*SequencedEvent)(nil),    // 11: tephra.v1.SequencedEvent
	(*ReadEvents)(nil),        // 12: tephra.v1.ReadEvents
	(*ReadEnd)(nil),           // 13: tephra.v1.ReadEnd
	(*SubscribeCaughtUp)(nil), // 14: tephra.v1.SubscribeCaughtUp
	(*StatsResponse)(nil),     // 15: tephra.v1.StatsResponse
	(*ErrorResponse)(nil),     // 16: tephra.v1.ErrorResponse
	(*Request)(nil),           // 17: tephra.v1.Request
	(*Response)(nil),          // 18: tephra.v1.Response
}
var file_tephra_v1_tephra_proto_depIdxs = []int32{
	2,  // 0: tephra.v1.Query.items:type_name -> tephra.v1.QueryItem
	3,  // 1: tephra.v1.AppendCondition.fail_if_events_match:type_name -> tephra.v1.Query
	1,  // 2: tephra.v1.AppendRequest.events:type_name -> tephra.v1.Event
	4,  // 3: tephra.v1.AppendRequest.condition:type_name -> tephra.v1.AppendCondition
	3,  // 4: tephra.v1.ReadRequest.query:type_name -> tephra.v1.Query
	3,  // 5: tephra.v1.SubscribeRequest.query:type_name -> tephra.v1.Query
	1,  // 6: tephra.v1.SequencedEvent.event:type_name -> tephra.v1.Event
	11, // 7: tephra.v1.ReadEvents.events:type_name -> tephra.v1.SequencedEvent
	0,  // 8: tephra.v1.ErrorResponse.code:type_name -> tephra.v1.ErrorCode
	5,  // 9: tephra.v1.Request.append:type_name -> tephra.v1.AppendRequest
	6,  // 10: tephra.v1.Request.read:type_name -> tephra.v1.ReadRequest
	7,  // 11: tephra.v1.Request.subscribe:type_name -> tephra.v1.SubscribeRequest
	8,  // 12: tephra.v1.Request.cancel:type_name -> tephra.v1.CancelRequest
	9,  // 13: tephra.v1.Request.stats:type_name -> tephra.v1.StatsRequest
	10, // 14: tephra.v1.Response.append:type_name -> tephra.v1.AppendResponse
	12, // 15: tephra.v1.Response.read_events:type_name -> tephra.v1.ReadEvents
	13, // 16: tephra.v1.Response.read_end:type_name -> tephra.v1.ReadEnd
	16, // 17: tephra.v1.Response.error:type_name -> tephra.v1.ErrorResponse
	14, // 18: tephra.v1.Response.caught_up:type_name -> tephra.v1.SubscribeCaughtUp
	15, // 19: tephra.v1.Response.stats:type_name -> tephra.v1.StatsResponse
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_tephra_v1_tephra_proto_init() }
func file_tephra_v1_tephra_proto_init() {
	if File_tephra_v1_tephra_proto != nil {
		return
	}
	file_tephra_v1_tephra_proto_msgTypes[4].OneofWrappers = []any{}
	file_tephra_v1_tephra_proto_msgTypes[5].OneofWrappers = []any{}
	file_tephra_v1_tephra_proto_msgTypes[15].OneofWrappers = []any{}
	file_tephra_v1_tephra_proto_msgTypes[16].OneofWrappers = []any{
		(*Request_Append)(nil),
		(*Request_Read)(nil),
		(*Request_Subscribe)(nil),
		(*Request_Cancel)(nil),
		(*Request_Stats)(nil),
	}
	file_tephra_v1_tephra_proto_msgTypes[17].OneofWrappers = []any{
		(*Response_Append)(nil),
		(*Response_ReadEvents)(nil),
		(*Response_ReadEnd)(nil),
		(*Response_Error)(nil),
		(*Response_CaughtUp)(nil),
		(*Response_Stats)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tephra_v1_tephra_proto_rawDesc), len(file_tephra_v1_tephra_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tephra_v1_tephra_proto_goTypes,
		DependencyIndexes: file_tephra_v1_tephra_proto_depIdxs,
		EnumInfos:         file_tephra_v1_tephra_proto_enumTypes,
		MessageInfos:      file_tephra_v1_tephra_proto_msgTypes,
	}.Build()
	File_tephra_v1_tephra_proto = out.File
	file_tephra_v1_tephra_proto_goTypes = nil
	file_tephra_v1_tephra_proto_depIdxs = nil
}
